services:
  # Main VATSIM monitoring service (headless)
  vatsim-monitor:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vatsim-tower-monitor
    restart: unless-stopped
    
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      - APP_ENV=production
      - FLASK_ENV=production
      - PUSHOVER_API_TOKEN=${PUSHOVER_API_TOKEN:-""}
      - PUSHOVER_USER_KEY=${PUSHOVER_USER_KEY:-""}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-30}
      - AIRPORT_CODE=${AIRPORT_CODE:-KOAK}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///prod_data/users.db}
    
    volumes:
      - ./logs:/app/logs
      - ./prod_data:/app/prod_data
    
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/tmp/vatsim_monitor_headless.lock') else 1)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    networks:
      - app-network

  # Web API service
  web-api:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: vatsim-web-api
    restart: unless-stopped
    
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      - APP_ENV=production
      - FLASK_ENV=production
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-4}
      - GUNICORN_BIND=0.0.0.0:8080
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///prod_data/users.db}
    
    volumes:
      - ./logs:/app/logs
      - ./prod_data:/app/prod_data
    
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.2'

    command: >
      gunicorn --bind ${GUNICORN_BIND:-0.0.0.0:8080}
               --workers ${GUNICORN_WORKERS:-2}
               --timeout ${GUNICORN_TIMEOUT:-120}
               --access-logfile '-'
               --error-logfile '-'
               'web.backend.app:app'
     
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    networks:
      - app-network

  # Nginx reverse proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: vatsim-nginx
    restart: unless-stopped
    
    ports:
      - "80:80"
      - "443:443"
    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    
    depends_on:
      - web-api
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    networks:
      - app-network

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: vatsim-certbot
    restart: on-failure
    
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    
    command: certonly --webroot -w /var/www/certbot --non-interactive --agree-tos --email ${SSL_EMAIL} -d ${DOMAIN_NAME} --staple-ocsp

networks:
  app-network:
    driver: bridge

volumes:
  certbot-conf:
  certbot-www: